# Generated by Django 4.2 on 2023-08-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=80)),
                ('fname', models.CharField(max_length=89)),
                ('lname', models.CharField(max_length=88)),
                ('email', models.EmailField(max_length=90)),
                ('pass1', models.CharField(max_length=90)),
                ('pass2', models.CharField(max_length=90)),
            ],
        ),
    ]
