# Generated by Django 4.2 on 2023-08-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=540)),
                ('area', models.CharField(max_length=90, null='True')),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=340)),
                ('country', models.CharField(max_length=120)),
            ],
        ),
    ]
