# Generated by Django 4.2 on 2023-09-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_stations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=250)),
                ('vehicleno', models.CharField(max_length=540)),
                ('mobileno', models.CharField(max_length=90, null='True')),
                ('city', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=340)),
                ('time', models.CharField(max_length=120)),
            ],
        ),
    ]
