# Generated by Django 4.2 on 2023-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_bookslots_accountno_bookslots_hname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(default='0', max_length=120)),
                ('accountno', models.CharField(default='0', max_length=120)),
                ('ifsccode', models.CharField(default='0', max_length=120)),
                ('total', models.CharField(default='0', max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookslots',
            name='accountno',
        ),
        migrations.RemoveField(
            model_name='bookslots',
            name='hname',
        ),
        migrations.RemoveField(
            model_name='bookslots',
            name='ifsccode',
        ),
        migrations.RemoveField(
            model_name='bookslots',
            name='total',
        ),
    ]
