# Generated by Django 4.2 on 2023-09-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_stationowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stations',
            old_name='country',
            new_name='ctslot',
        ),
        migrations.RenameField(
            model_name='stations',
            old_name='state',
            new_name='phone',
        ),
    ]
