# Generated by Django 4.2 on 2023-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='Location',
            field=models.CharField(default='0', max_length=290),
        ),
        migrations.AddField(
            model_name='stations',
            name='details',
            field=models.CharField(default='0', max_length=290),
        ),
    ]
