# Generated by Django 4.2 on 2023-10-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_stations_location_stations_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslots',
            name='date',
            field=models.CharField(default='0', max_length=120),
        ),
    ]
