# Generated by Django 4.2 on 2024-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0013_deletedbooking_accountno_deletedbooking_hname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hybrid_Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=540)),
                ('area', models.CharField(max_length=90, null='True')),
                ('sockets', models.CharField(max_length=250, null='True')),
                ('city', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=340)),
                ('ctslot', models.CharField(max_length=120)),
                ('details', models.CharField(default='0', max_length=290)),
                ('Location', models.CharField(default='0', max_length=290)),
            ],
        ),
        migrations.CreateModel(
            name='Offgrid_Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=540)),
                ('area', models.CharField(max_length=90, null='True')),
                ('sockets', models.CharField(max_length=250, null='True')),
                ('city', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=340)),
                ('ctslot', models.CharField(max_length=120)),
                ('details', models.CharField(default='0', max_length=290)),
                ('Location', models.CharField(default='0', max_length=290)),
            ],
        ),
    ]
